services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\:
    resource: './'

  App\Infrastructure\Controller\:
    resource: './Controller'
    tags:
      - { name: controller.service_arguments }

  Monolog\Handler\TelegramBotHandler:
    arguments:
      $apiKey: '%env(TELEGRAM_BOT_KEY)%'
      $channel: '%env(TELEGRAM_CHANNEL)%'
