services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Security\:
    resource: '../'
    exclude:
      - '../Entity/'
      - '../Model/'

  App\Security\Controller\:
    resource: '../Controller'
    tags:
      - { name: controller.service_arguments }
