doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '14.2'
        charset: utf8
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
