twig:
    paths:
        '%kernel.project_dir%/src/Infrastructure/Resources/templates': infrastructure
        '%kernel.project_dir%/src/Security/Resources/templates': security
        '%kernel.project_dir%/src/Profile/Resources/templates': profile
        '%kernel.project_dir%/src/Learning/Resources/templates': learning

when@test:
    twig:
        strict_variables: true
