twig:
    paths:
        '%kernel.project_dir%/src/Infrastructure/templates': infrastructure
        '%kernel.project_dir%/src/Security/templates': security

when@test:
    twig:
        strict_variables: true
