version: '3.9'

services:
  # database:
  #   image: postgres:14.2-alpine
  #   command: postgres -c listen_addresses=*
  #   environment:
  #     - TZ=UTC
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - pgdata_14_2:/var/lib/postgresql/data
  #   ports:
  #     - '5722:${DB_PORT}'
  #   restart: always

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        COMPOSER_GITHUB_TOKEN: ${COMPOSER_GITHUB_TOKEN}
        LINUX_USER_ID: ${LINUX_USER_ID}
    environment:
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=9029
      PHP_IDE_CONFIG: serverName=learning
    tty: true
    # depends_on:
    #   - database
    volumes:
      - ./docker/.zsh_history:/home/docker/.zsh_history
      - ./:/srv/app
    restart: always

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/:/srv/app/public
    depends_on:
      - php
    ports:
      - '8041:80'
    restart: always

volumes:
    pgdata_14_2:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.231.0/28
