version: '3.9'

services:
  database:
    image: postgres:14.2-alpine
    command: postgres -c listen_addresses=*
    environment:
      - TZ=UTC
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata_14_2:/var/lib/postgresql/data
    ports:
      - '${DB_EXTERNAL_PORT}:${DB_PORT}'
    restart: always

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        COMPOSER_GITHUB_TOKEN: ${COMPOSER_GITHUB_TOKEN}
        LINUX_USER_ID: ${LINUX_USER_ID}
    environment:
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_REMOTE_PORT}
      PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
    tty: true
    depends_on:
      - database
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/.zsh_history:/home/docker/.zsh_history
      - ./:/srv/app
    restart: always

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/:/srv/app/public
    depends_on:
      - php
    ports:
      - '${WEBSERVER_EXTERNAL_PORT}:80'
    restart: always

  encore-watcher:
    image: node:16.15-alpine3.15
    command: npm run watch
    working_dir: /srv/app
    user: '${LINUX_USER_ID}:${LINUX_USER_ID}'
    volumes:
      - ./:/srv/app
    tty: true
    restart: always

  npm-installer:
    image: node:16.15-alpine3.15
    command: npm ci
    working_dir: /srv/app
    user: '${LINUX_USER_ID}:${LINUX_USER_ID}'
    volumes:
      - ./:/srv/app
    tty: true

  php-builder:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        COMPOSER_GITHUB_TOKEN: ${COMPOSER_GITHUB_TOKEN}
        LINUX_USER_ID: ${LINUX_USER_ID}
    command: make build
    depends_on:
      - database
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/srv/app

  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]

volumes:
  pgdata_14_2:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.231.0/28
