services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Learning\:
    resource: './'
    exclude:
      - './Entity/'

  App\Learning\Controller\:
    resource: './Controller'
    tags:
      - { name: controller.service_arguments }

  App\Learning\Service\LearningStrategy\LearningStrategyContext:
    calls:
      - method: addStrategy
        arguments:
          - '@App\Learning\Service\LearningStrategy\Strategy\WeightedRandomStrategy'