services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Profile\:
    resource: './'
    exclude:
      - './Entity/'

  App\Profile\Controller\:
    resource: './Controller'
    tags:
      - { name: controller.service_arguments }
