services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Profile\:
    resource: './'
    exclude:
      - './Entity/'
      - './Model/'

  App\Profile\Controller\:
    resource: './Controller'
    tags:
      - { name: controller.service_arguments }

  App\Profile\Service\RegistrationService:
    arguments:
      $emailFrom: '%env(string:MAILER_FROM)%'
      $host: '%env(string:APP_HOST)%'
