services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Security\:
    resource: './'
    exclude:
      - './Entity/'

  App\Security\Controller\:
    resource: './Controller'
    tags:
      - { name: controller.service_arguments }

parameters:
  app.host: '%env(APP_HOST)%'
